name: deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "22.14.0"

            - name: install deps and build
              run: |
                  npm install
                  npm run build
                  npx prisma generate

            - name: deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DO_HOST }}
                  username: ${{ secrets.DO_USERNAME }}
                  key: ${{ secrets.DO_SSH_KEY }}
                  script: |
                      set -e
                      cd /home/tabish/fdba-backend
                      git pull origin main
                      /home/tabish/.nvm/versions/node/v22.14.0/bin/npm install
                      /home/tabish/.nvm/versions/node/v22.14.0/bin/pm2 restart --update-env 0
                      echo "deployment success!"
